version: '3'

services:
  db:
    image: mysql/mysql-server:latest
    container_name: db
    environment:
      MYSQL_DATABASE: 'electiondb'
      MYSQL_USER: 'ck'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - my-db:/usr/local/bin/mysql

  backend:
    image: docker123chetan/evoting_backend:latest
    container_name: backend

    ports:
      - '8083:8083'

    restart: always

    depends_on:
      - db

  frontend:
    image: docker123chetan/frontendimage:latest
    container_name: frontend

    ports:
      - "3000:3000"

    restart: always

    depends_on:
      - backend
volumes:
  my-db: